[project]
name = "programering-data-plattform-julius-falt-skoglund"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "fastapi[standard]",
  "pandas>=3.0.0",
  "psycopg[binary]",
  "python-dotenv",
]
